name: my_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  
  
  socket_io_client: ^2.0.3
  audioplayers: ^6.5.0
  record: ^6.1.0
  audio_session: ^0.1.6
  flutter_sound_platform_interface: ^9.2.13
  background_fetch: ^1.2.3


  # 저장소
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.0.15

  # 블루투스 & 오디오
  flutter_bluetooth_serial: ^0.4.0
  flutter_sound: ^9.28.0
  just_audio: ^0.9.36

  # 음성 인식
  speech_to_text: ^7.0.0

  # 네트워크 & 권한
  http: ^0.13.6
  permission_handler: ^10.2.0
  url_launcher: ^6.2.5
  uni_links: ^0.5.1

  # UI
  provider: ^6.1.5
  fl_chart: ^1.0.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.2

  # 헬스
  health: ^13.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 코드 생성 도구
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/opening.png
    - lib/assets/profile.jpg
    - lib/assets/koala.png
    - assets/google_icon.png
    - assets/sounds/
    - assets/audio/sample.mp3
    - .env
