name: my_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  speech_to_text: ^7.0.0
  flutter_sound: ^9.28.0
  fl_chart: ^1.0.0
  
  http: ^0.13.6
  flutter_secure_storage: ^9.0.0
  health: ^13.1.1
  permission_handler: ^10.2.0


  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.2

  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  url_launcher: ^6.2.5
  uni_links: ^0.5.1
  shared_preferences: ^2.0.15

  just_audio: ^0.9.36  # ✅ 추가된 오디오 패키지

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/opening.png
    - lib/assets/profile.jpg
    - lib/assets/koala.png
    - assets/google_icon.png

    - assets/sounds/   # ✅ 사운드 폴더가 있다면 반드시 등록

